const quotesList = () => {
  return [
    {
      q: "Know yourself and you will win all battles.",
      a: "Sun Tzu",
      h: "<blockquote>&ldquo;Know yourself and you will win all battles.&rdquo; &mdash; <footer>Sun Tzu</footer></blockquote>",
      id: 1,
    },
    {
      q: "The most tragic thing in the world is a man of genius who is not a man of honor.",
      a: "George Bernard Shaw",
      h: "<blockquote>&ldquo;The most tragic thing in the world is a man of genius who is not a man of honor.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
      id: 2,
    },
    {
      q: "If you could kick the person in the pants responsible for most of your trouble, you wouldn't sit for a month.",
      a: "Theodore Roosevelt",
      h: "<blockquote>&ldquo;If you could kick the person in the pants responsible for most of your trouble, you wouldn't sit for a month.&rdquo; &mdash; <footer>Theodore Roosevelt</footer></blockquote>",
      id: 3,
    },
    {
      q: "By failing to prepare, you are preparing to fail.",
      a: "Benjamin Franklin ",
      h: "<blockquote>&ldquo;By failing to prepare, you are preparing to fail.&rdquo; &mdash; <footer>Benjamin Franklin </footer></blockquote>",
      id: 4,
    },
    {
      q: "Winning isn't everything, but wanting to win is.",
      a: "Vince Lombardi",
      h: "<blockquote>&ldquo;Winning isn't everything, but wanting to win is.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>",
      id: 5,
    },
    {
      q: "I defeat my enemies when I make them my friends.",
      a: "Dalai Lama",
      h: "<blockquote>&ldquo;I defeat my enemies when I make them my friends.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
      id: 6,
    },
    {
      q: "Emancipate yourself from mental slavery, none but ourselves can free our mind.",
      a: "Bob Marley",
      h: "<blockquote>&ldquo;Emancipate yourself from mental slavery, none but ourselves can free our mind.&rdquo; &mdash; <footer>Bob Marley</footer></blockquote>",
      id: 7,
    },
    {
      q: "Life does not get better by chance, it gets better by change.",
      a: "Jim Rohn",
      h: "<blockquote>&ldquo;Life does not get better by chance, it gets better by change.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
      id: 8,
    },
    {
      q: "The whole world is a series of miracles, but we're so used to them we call them ordinary things.",
      a: "Hans Christian Andersen",
      h: "<blockquote>&ldquo;The whole world is a series of miracles, but we're so used to them we call them ordinary things.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
      id: 9,
    },
    {
      q: "Things do not have meaning. We assign meaning to everything.",
      a: "Tony Robbins",
      h: "<blockquote>&ldquo;Things do not have meaning. We assign meaning to everything.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
      id: 10,
    },
    {
      q: "If you see a get rich quick scheme, that's someone else trying to get rich off of you.",
      a: "Naval Ravikant",
      h: "<blockquote>&ldquo;If you see a get rich quick scheme, that's someone else trying to get rich off of you.&rdquo; &mdash; <footer>Naval Ravikant</footer></blockquote>",
      id: 11,
    },
    {
      q: "We are all different. Don't judge, understand instead.",
      a: "Roy T. Bennett",
      h: "<blockquote>&ldquo;We are all different. Don't judge, understand instead.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
      id: 12,
    },
    {
      q: "an action committed in anger is an action doomed to failure. ",
      a: "Genghis Khan",
      h: "<blockquote>&ldquo;an action committed in anger is an action doomed to failure. &rdquo; &mdash; <footer>Genghis Khan</footer></blockquote>",
      id: 13,
    },
    {
      q: "Some men see things as they are and ask why. Others dream things that never were and ask why not.",
      a: "George Bernard Shaw",
      h: "<blockquote>&ldquo;Some men see things as they are and ask why. Others dream things that never were and ask why not.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
      id: 14,
    },
    {
      q: "People are weird. When we find someone with weirdness that is compatible with ours, we team up and call it love.",
      a: "Dr. Seuss",
      h: "<blockquote>&ldquo;People are weird. When we find someone with weirdness that is compatible with ours, we team up and call it love.&rdquo; &mdash; <footer>Dr. Seuss</footer></blockquote>",
      id: 15,
    },
    {
      q: "You may delay, but time will not.",
      a: "Benjamin Franklin ",
      h: "<blockquote>&ldquo;You may delay, but time will not.&rdquo; &mdash; <footer>Benjamin Franklin </footer></blockquote>",
      id: 16,
    },
    {
      q: "Do the difficult things while they are easy and do the great things while they are small.",
      a: "Laozi",
      h: "<blockquote>&ldquo;Do the difficult things while they are easy and do the great things while they are small.&rdquo; &mdash; <footer>Laozi</footer></blockquote>",
      id: 17,
    },
    {
      q: "You will face many defeats in life, but never let yourself be defeated.",
      a: "Maya Angelou",
      h: "<blockquote>&ldquo;You will face many defeats in life, but never let yourself be defeated.&rdquo; &mdash; <footer>Maya Angelou</footer></blockquote>",
      id: 18,
    },
    {
      q: "Nothing ever happened in the past that can prevent you from being present now; and if the past cannot prevent you from being present now, what power does it have?",
      a: "Eckhart Tolle ",
      h: "<blockquote>&ldquo;Nothing ever happened in the past that can prevent you from being present now; and if the past cannot prevent you from being present now, what power does it have?&rdquo; &mdash; <footer>Eckhart Tolle </footer></blockquote>",
      id: 19,
    },
    {
      q: "One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.",
      a: "Elbert Hubbard",
      h: "<blockquote>&ldquo;One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
      id: 20,
    },
    {
      q: "If you do not change direction, you may end up where you are heading.",
      a: "Laozi",
      h: "<blockquote>&ldquo;If you do not change direction, you may end up where you are heading.&rdquo; &mdash; <footer>Laozi</footer></blockquote>",
      id: 21,
    },
    {
      q: "You can avoid reality, but you cannot avoid the consequences of avoiding reality.",
      a: "Ayn Rand",
      h: "<blockquote>&ldquo;You can avoid reality, but you cannot avoid the consequences of avoiding reality.&rdquo; &mdash; <footer>Ayn Rand</footer></blockquote>",
      id: 22,
    },
    {
      q: "Only one thing is ever guaranteed, that is that you will definitely not achieve the goal if you don't take the shot.",
      a: "Wayne Gretzky",
      h: "<blockquote>&ldquo;Only one thing is ever guaranteed, that is that you will definitely not achieve the goal if you don't take the shot.&rdquo; &mdash; <footer>Wayne Gretzky</footer></blockquote>",
      id: 23,
    },
    {
      q: "Those who cannot change their minds cannot change anything.",
      a: "George Bernard Shaw",
      h: "<blockquote>&ldquo;Those who cannot change their minds cannot change anything.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
      id: 24,
    },
    {
      q: "Identify your problems, but give your power and energy to solutions.",
      a: "Tony Robbins",
      h: "<blockquote>&ldquo;Identify your problems, but give your power and energy to solutions.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
      id: 25,
    },
    {
      q: "You are the only real obstacle in your path to a fulfilling life.",
      a: "Les Brown",
      h: "<blockquote>&ldquo;You are the only real obstacle in your path to a fulfilling life.&rdquo; &mdash; <footer>Les Brown</footer></blockquote>",
      id: 26,
    },
    {
      q: "Make improvements, not excuses. Seek respect, not attention.",
      a: "Roy T. Bennett",
      h: "<blockquote>&ldquo;Make improvements, not excuses. Seek respect, not attention.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
      id: 27,
    },
    {
      q: "You were born to win, but to be a winner you must plan to win, prepare to win, and expect to win.",
      a: "Zig Ziglar",
      h: "<blockquote>&ldquo;You were born to win, but to be a winner you must plan to win, prepare to win, and expect to win.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
      id: 28,
    },
    {
      q: "To earn more you must learn more.",
      a: "Brian Tracy",
      h: "<blockquote>&ldquo;To earn more you must learn more.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
      id: 29,
    },
    {
      q: "I wasn't brave, I just didn't have time to be scared.",
      a: "Amelia Earhart",
      h: "<blockquote>&ldquo;I wasn't brave, I just didn't have time to be scared.&rdquo; &mdash; <footer>Amelia Earhart</footer></blockquote>",
      id: 30,
    },
    {
      q: "Don't give up on your dreams, or your dreams will give up on you.",
      a: "John Wooden",
      h: "<blockquote>&ldquo;Don't give up on your dreams, or your dreams will give up on you.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
      id: 31,
    },
    {
      q: "Everything you look at can become a fairy tale and you can get a story from everything you touch.",
      a: "Hans Christian Andersen",
      h: "<blockquote>&ldquo;Everything you look at can become a fairy tale and you can get a story from everything you touch.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
      id: 32,
    },
    {
      q: "The single biggest problem in communication is the illusion that it has taken place.",
      a: "George Bernard Shaw",
      h: "<blockquote>&ldquo;The single biggest problem in communication is the illusion that it has taken place.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
      id: 33,
    },
    {
      q: "The way to change others' minds is with affection, and not anger.",
      a: "Dalai Lama",
      h: "<blockquote>&ldquo;The way to change others' minds is with affection, and not anger.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
      id: 34,
    },
    {
      q: "Most people dabble their way through life, never deciding to master anything in particular.",
      a: "Tony Robbins",
      h: "<blockquote>&ldquo;Most people dabble their way through life, never deciding to master anything in particular.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
      id: 35,
    },
    {
      q: "Science can flourish only in an atmosphere of free speech. ",
      a: "Albert Einstein",
      h: "<blockquote>&ldquo;Science can flourish only in an atmosphere of free speech. &rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
      id: 36,
    },
    {
      q: "Fear is stupid. So are regrets.",
      a: "Marilyn Monroe",
      h: "<blockquote>&ldquo;Fear is stupid. So are regrets.&rdquo; &mdash; <footer>Marilyn Monroe</footer></blockquote>",
      id: 37,
    },
    {
      q: "Life must be rich and full of loving-it's no good otherwise, no good at all, for anyone.  ",
      a: "Jack Kerouac",
      h: "<blockquote>&ldquo;Life must be rich and full of loving-it's no good otherwise, no good at all, for anyone.  &rdquo; &mdash; <footer>Jack Kerouac</footer></blockquote>",
      id: 38,
    },
    {
      q: "Far and away the best prize that life has to offer is the chance to work hard at work worth doing.",
      a: "Theodore Roosevelt",
      h: "<blockquote>&ldquo;Far and away the best prize that life has to offer is the chance to work hard at work worth doing.&rdquo; &mdash; <footer>Theodore Roosevelt</footer></blockquote>",
      id: 39,
    },
    {
      q: "You may be disappointed if you fail, but you are doomed if you don't try. ",
      a: "Beverly Sills",
      h: "<blockquote>&ldquo;You may be disappointed if you fail, but you are doomed if you don't try. &rdquo; &mdash; <footer>Beverly Sills</footer></blockquote>",
      id: 40,
    },
    {
      q: "Live and act within the limit of your knowledge and keep expanding it to the limit of your life.",
      a: "Ayn Rand",
      h: "<blockquote>&ldquo;Live and act within the limit of your knowledge and keep expanding it to the limit of your life.&rdquo; &mdash; <footer>Ayn Rand</footer></blockquote>",
      id: 41,
    },
    {
      q: "Any fool can paint a picture, but it takes a wise man to be able to sell it.",
      a: "Samuel Butler",
      h: "<blockquote>&ldquo;Any fool can paint a picture, but it takes a wise man to be able to sell it.&rdquo; &mdash; <footer>Samuel Butler</footer></blockquote>",
      id: 42,
    },
    {
      q: "Curiosity is the most powerful thing you own.",
      a: "James Cameron",
      h: "<blockquote>&ldquo;Curiosity is the most powerful thing you own.&rdquo; &mdash; <footer>James Cameron</footer></blockquote>",
      id: 43,
    },
    {
      q: "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. ",
      a: "Henry Ford",
      h: "<blockquote>&ldquo;Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. &rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
      id: 44,
    },
    {
      q: "What worries you, masters you.",
      a: "John Locke",
      h: "<blockquote>&ldquo;What worries you, masters you.&rdquo; &mdash; <footer>John Locke</footer></blockquote>",
      id: 45,
    },
    {
      q: "Blessed is he who expects nothing, for he shall never be disappointed.",
      a: "Alexander Pope",
      h: "<blockquote>&ldquo;Blessed is he who expects nothing, for he shall never be disappointed.&rdquo; &mdash; <footer>Alexander Pope</footer></blockquote>",
      id: 46,
    },
    {
      q: "The greatest test of courage on earth is to bear defeat without losing heart.",
      a: "Robert Greene",
      h: "<blockquote>&ldquo;The greatest test of courage on earth is to bear defeat without losing heart.&rdquo; &mdash; <footer>Robert Greene</footer></blockquote>",
      id: 47,
    },
    {
      q: "Understanding that rests in what it does not understand is the finest.",
      a: "Zhuangzi",
      h: "<blockquote>&ldquo;Understanding that rests in what it does not understand is the finest.&rdquo; &mdash; <footer>Zhuangzi</footer></blockquote>",
      id: 48,
    },
    {
      q: "I will love the light for it shows me the way, yet I will endure the darkness because it shows me the stars.",
      a: "Og Mandino",
      h: "<blockquote>&ldquo;I will love the light for it shows me the way, yet I will endure the darkness because it shows me the stars.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
      id: 49,
    },
    {
      q: "A single dream is more powerful than a thousand realities.",
      a: "J.R.R. Tolkien",
      h: "<blockquote>&ldquo;A single dream is more powerful than a thousand realities.&rdquo; &mdash; <footer>J.R.R. Tolkien</footer></blockquote>",
      id: 50,
    },
  ];
};

export default quotesList;
