const ratingQuotes = () => {
  return [
    {
      q: "Health is the greatest of all possessions.",
      a: "Jonathan Swift",
      h: "<blockquote>&ldquo;Health is the greatest of all possessions.&rdquo; &mdash; <footer>Jonathan Swift</footer></blockquote>",
      rating_id: 1,
    },
    {
      q: "Nothing is more real than nothing.",
      a: "Samuel Beckett",
      h: "<blockquote>&ldquo;Nothing is more real than nothing.&rdquo; &mdash; <footer>Samuel Beckett</footer></blockquote>",
      rating_id: 1,
    },
    {
      q: "Do the difficult things while they are easy and do the great things while they are small.",
      a: "Laozi",
      h: "<blockquote>&ldquo;Do the difficult things while they are easy and do the great things while they are small.&rdquo; &mdash; <footer>Laozi</footer></blockquote>",
      rating_id: 1,
    },
    {
      q: "Sometimes you have to shut your eyes, so you can see the real beauty.",
      a: "Kilian Jornet",
      h: "<blockquote>&ldquo;Sometimes you have to shut your eyes, so you can see the real beauty.&rdquo; &mdash; <footer>Kilian Jornet</footer></blockquote>",
      rating_id: 1,
    },
    {
      q: "If you genuinely want something, don't wait for it - teach yourself.",
      a: "Gurbaksh Chahal",
      h: "<blockquote>&ldquo;If you genuinely want something, don't wait for it - teach yourself.&rdquo; &mdash; <footer>Gurbaksh Chahal</footer></blockquote>",
      rating_id: 2,
    },
    {
      q: "Just do what must be done. This may not be happiness but it is greatness.",
      a: "George Bernard Shaw",
      h: "<blockquote>&ldquo;Just do what must be done. This may not be happiness but it is greatness.&rdquo; &mdash; <footer>George Bernard Shaw</footer></blockquote>",
      rating_id: 2,
    },
    {
      q: "If you don't know where you're going, you will probably end up somewhere else.",
      a: "Laurence J. Peter",
      h: "<blockquote>&ldquo;If you don't know where you're going, you will probably end up somewhere else.&rdquo; &mdash; <footer>Laurence J. Peter</footer></blockquote>",
      rating_id: 2,
    },
    {
      q: "When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.",
      a: "Zig Ziglar",
      h: "<blockquote>&ldquo;When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
      rating_id: 2,
    },
    {
      q: "Conscience is a man's compass. ",
      a: "Vincent van Gogh",
      h: "<blockquote>&ldquo;Conscience is a man's compass. &rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
      rating_id: 3,
    },
    {
      q: "Confidence breeds beauty.  ",
      a: "Estee Lauder",
      h: "<blockquote>&ldquo;Confidence breeds beauty.  &rdquo; &mdash; <footer>Estee Lauder</footer></blockquote>",
      rating_id: 3,
    },
    {
      q: "Go confidently in the direction of your dreams! Live the life you've imagined.",
      a: "Henry David Thoreau",
      h: "<blockquote>&ldquo;Go confidently in the direction of your dreams! Live the life you've imagined.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
      rating_id: 3,
    },
    {
      q: "The eyes of others our prisons; their thoughts our cages.",
      a: "Virginia Woolf",
      h: "<blockquote>&ldquo;The eyes of others our prisons; their thoughts our cages.&rdquo; &mdash; <footer>Virginia Woolf</footer></blockquote>",
      rating_id: 4,
    },
    {
      q: "Courage is found in unlikely places.",
      a: "J.R.R. Tolkien",
      h: "<blockquote>&ldquo;Courage is found in unlikely places.&rdquo; &mdash; <footer>J.R.R. Tolkien</footer></blockquote>",
      rating_id: 4,
    },
    {
      q: "Just as true humor is laughter at oneself, true humanity is knowledge of oneself.",
      a: "Alan Watts",
      h: "<blockquote>&ldquo;Just as true humor is laughter at oneself, true humanity is knowledge of oneself.&rdquo; &mdash; <footer>Alan Watts</footer></blockquote>",
      rating_id: 4,
    },
    {
      q: "The road to success and the road to failure are almost exactly the same.",
      a: "Colin R. Davis",
      h: "<blockquote>&ldquo;The road to success and the road to failure are almost exactly the same.&rdquo; &mdash; <footer>Colin R. Davis</footer></blockquote>",
      rating_id: 4,
    },
    {
      q: "When you are tough on yourself, life is going to be infinitely easier on you.  ",
      a: "Zig Ziglar",
      h: "<blockquote>&ldquo;When you are tough on yourself, life is going to be infinitely easier on you.  &rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
      rating_id: 4,
    },
    {
      q: "It is well known that those who do not trust themselves never trust others.",
      a: "Alfred Adler",
      h: "<blockquote>&ldquo;It is well known that those who do not trust themselves never trust others.&rdquo; &mdash; <footer>Alfred Adler</footer></blockquote>",
      rating_id: 5,
    },
    {
      q: "No duty is more urgent than that of returning thanks.",
      a: "James Allen",
      h: "<blockquote>&ldquo;No duty is more urgent than that of returning thanks.&rdquo; &mdash; <footer>James Allen</footer></blockquote>",
      rating_id: 5,
    },
    {
      q: "Be curious, not judgmental.",
      a: "Walt Whitman",
      h: "<blockquote>&ldquo;Be curious, not judgmental.&rdquo; &mdash; <footer>Walt Whitman</footer></blockquote>",
      rating_id: 5,
    },
    {
      q: "Reversing your treatment of the man you have wronged is better than asking his forgiveness.",
      a: "Elbert Hubbard",
      h: "<blockquote>&ldquo;Reversing your treatment of the man you have wronged is better than asking his forgiveness.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
      rating_id: 5,
    },
    {
      q: "Ideas do not reach perfection in a day, no matter how much study is put upon them.",
      a: "Alexander Graham Bell",
      h: "<blockquote>&ldquo;Ideas do not reach perfection in a day, no matter how much study is put upon them.&rdquo; &mdash; <footer>Alexander Graham Bell</footer></blockquote>",
      rating_id: 6,
    },
    {
      q: "A very little key will open a very heavy door.",
      a: "Charles Dickens",
      h: "<blockquote>&ldquo;A very little key will open a very heavy door.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
      rating_id: 6,
    },
    {
      q: "The past has no power over the present moment. ",
      a: "Eckhart Tolle ",
      h: "<blockquote>&ldquo;The past has no power over the present moment. &rdquo; &mdash; <footer>Eckhart Tolle </footer></blockquote>",
      rating_id: 6,
    },
    {
      q: "Society is composed of two great classes those who have more dinners than appetite, and those who have more appetite than dinners.",
      a: "Nicolas Chamfort",
      h: "<blockquote>&ldquo;Society is composed of two great classes those who have more dinners than appetite, and those who have more appetite than dinners.&rdquo; &mdash; <footer>Nicolas Chamfort</footer></blockquote>",
      rating_id: 6,
    },
    {
      q: "The more tranquil a man becomes, the greater is his success, his influence, his power for good. Calmness of mind is one of the beautiful jewels of wisdom.",
      a: "James Allen",
      h: "<blockquote>&ldquo;The more tranquil a man becomes, the greater is his success, his influence, his power for good. Calmness of mind is one of the beautiful jewels of wisdom.&rdquo; &mdash; <footer>James Allen</footer></blockquote>",
      rating_id: 7,
    },
    {
      q: "Great acts are made up of small deeds.",
      a: "Lao Tzu",
      h: "<blockquote>&ldquo;Great acts are made up of small deeds.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
      rating_id: 7,
    },
    {
      q: "You can tell more about a person by what he says about others than you can by what others say about him.",
      a: "Audrey Hepburn",
      h: "<blockquote>&ldquo;You can tell more about a person by what he says about others than you can by what others say about him.&rdquo; &mdash; <footer>Audrey Hepburn</footer></blockquote>",
      rating_id: 7,
    },
    {
      q: "In the midst of chaos, there is also opportunity.",
      a: "Sun Tzu",
      h: "<blockquote>&ldquo;In the midst of chaos, there is also opportunity.&rdquo; &mdash; <footer>Sun Tzu</footer></blockquote>",
      rating_id: 7,
    },
    {
      q: "Freeing oneself from words is liberation. ",
      a: "Bodhidharma",
      h: "<blockquote>&ldquo;Freeing oneself from words is liberation. &rdquo; &mdash; <footer>Bodhidharma</footer></blockquote>",
      rating_id: 7,
    },
    {
      q: "Remain calm. Be kind.",
      a: "Colin Powell",
      h: "<blockquote>&ldquo;Remain calm. Be kind.&rdquo; &mdash; <footer>Colin Powell</footer></blockquote>",
      rating_id: 8,
    },
    {
      q: "You will face many defeats in life, but never let yourself be defeated.",
      a: "Maya Angelou",
      h: "<blockquote>&ldquo;You will face many defeats in life, but never let yourself be defeated.&rdquo; &mdash; <footer>Maya Angelou</footer></blockquote>",
      rating_id: 8,
    },
    {
      q: "Whoever is happy will make others happy too.",
      a: "Anne Frank",
      h: "<blockquote>&ldquo;Whoever is happy will make others happy too.&rdquo; &mdash; <footer>Anne Frank</footer></blockquote>",
      rating_id: 8,
    },
    {
      q: "Our greatest glory is not in never falling, but in rising every time we fall. ",
      a: "Confucius ",
      h: "<blockquote>&ldquo;Our greatest glory is not in never falling, but in rising every time we fall. &rdquo; &mdash; <footer>Confucius </footer></blockquote>",
      rating_id: 8,
    },
    {
      q: "He who is not contented with what he has, would not be contented with what he would like to have.",
      a: "Socrates",
      h: "<blockquote>&ldquo;He who is not contented with what he has, would not be contented with what he would like to have.&rdquo; &mdash; <footer>Socrates</footer></blockquote>",
      rating_id: 8,
    },
    {
      q: "It is not uncommon for people to spend their whole life waiting to start living.",
      a: "Eckhart Tolle ",
      h: "<blockquote>&ldquo;It is not uncommon for people to spend their whole life waiting to start living.&rdquo; &mdash; <footer>Eckhart Tolle </footer></blockquote>",
      rating_id: 9,
    },
    {
      q: "Care about what other people think and you will always be their prisoner.",
      a: "Lao Tzu",
      h: "<blockquote>&ldquo;Care about what other people think and you will always be their prisoner.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
      rating_id: 9,
    },
    {
      q: "As you think, you travel, and as you love, you attract.",
      a: "James Allen",
      h: "<blockquote>&ldquo;As you think, you travel, and as you love, you attract.&rdquo; &mdash; <footer>James Allen</footer></blockquote>",
      rating_id: 9,
    },
    {
      q: "You can have it all. You just can't have it all at once. ",
      a: "Oprah Winfrey",
      h: "<blockquote>&ldquo;You can have it all. You just can't have it all at once. &rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
      rating_id: 10,
    },
    {
      q: "We may not be responsible for the world that created our minds, but we can take responsibility for the mind with which we create our world.",
      a: "Gabor Mate'",
      h: "<blockquote>&ldquo;We may not be responsible for the world that created our minds, but we can take responsibility for the mind with which we create our world.&rdquo; &mdash; <footer>Gabor Mate'</footer></blockquote>",
      rating_id: 10,
    },
    {
      q: "Most people spend more time and energy going around problems than in trying to solve them. ",
      a: "Henry Ford",
      h: "<blockquote>&ldquo;Most people spend more time and energy going around problems than in trying to solve them. &rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
      rating_id: 10,
    },
    {
      q: "You may delay, but time will not.",
      a: "Benjamin Franklin ",
      h: "<blockquote>&ldquo;You may delay, but time will not.&rdquo; &mdash; <footer>Benjamin Franklin </footer></blockquote>",
      rating_id: 10,
    },
    {
      q: "To do great work one must be very idle as well as very industrious.",
      a: "Samuel Butler",
      h: "<blockquote>&ldquo;To do great work one must be very idle as well as very industrious.&rdquo; &mdash; <footer>Samuel Butler</footer></blockquote>",
      rating_id: 10,
    },
    {
      q: "Do all things with love.",
      a: "Og Mandino",
      h: "<blockquote>&ldquo;Do all things with love.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
      rating_id: 10,
    },
    {
      q: "It is not uncommon for people to spend their whole life waiting to start living.",
      a: "Eckhart Tolle ",
      h: "<blockquote>&ldquo;It is not uncommon for people to spend their whole life waiting to start living.&rdquo; &mdash; <footer>Eckhart Tolle </footer></blockquote>",
      rating_id: 1,
    },
    {
      q: "When one door closes another door opens. ",
      a: "Alexander Graham Bell",
      h: "<blockquote>&ldquo;When one door closes another door opens. &rdquo; &mdash; <footer>Alexander Graham Bell</footer></blockquote>",
      rating_id: 2,
    },
    {
      q: "The eyes of others our prisons; their thoughts our cages.",
      a: "Virginia Woolf",
      h: "<blockquote>&ldquo;The eyes of others our prisons; their thoughts our cages.&rdquo; &mdash; <footer>Virginia Woolf</footer></blockquote>",
      rating_id: 3,
    },
    {
      q: "The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers.",
      a: "Amelia Earhart",
      h: "<blockquote>&ldquo;The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers.&rdquo; &mdash; <footer>Amelia Earhart</footer></blockquote>",
      rating_id: 4,
    },
    {
      q: "The biggest adventure you can ever take is to live the life of your dreams. ",
      a: "Oprah Winfrey",
      h: "<blockquote>&ldquo;The biggest adventure you can ever take is to live the life of your dreams. &rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
      rating_id: 5,
    },
    {
      q: "There is no failure except in no longer trying. There is no defeat except from within, no insurmountable barrier except our own inherent weakness of purpose.",
      a: "Elbert Hubbard",
      h: "<blockquote>&ldquo;There is no failure except in no longer trying. There is no defeat except from within, no insurmountable barrier except our own inherent weakness of purpose.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
      rating_id: 6,
    },
    {
      q: "Live life as though nobody is watching, and express yourself as though everyone is listening.",
      a: "Nelson Mandela",
      h: "<blockquote>&ldquo;Live life as though nobody is watching, and express yourself as though everyone is listening.&rdquo; &mdash; <footer>Nelson Mandela</footer></blockquote>",
      rating_id: 7,
    },
  ];
};

export default ratingQuotes;
